name: CI

on:
  pull_request:
    branches: "*"
  push:
    branches: master
  schedule:
    - cron: "0 7 * * 1"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - crystal_version: 1.18.2
            lint: true

    runs-on: ubuntu-latest

    env:
      SQLITE_VERSION: ${{ matrix.sqlite_version }}
      SQLITE_YEAR: ${{ matrix.sqlite_year }}

    steps:
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{matrix.crystal_version}}

      - name: Donwload sources
        uses: actions/checkout@v2

      - name: Check formatting
        if: ${{ matrix.lint }}
        run: crystal tool format --check

      - name: Install dependencies
        run: |
          shards install

      - name: Run linter
        if: ${{ matrix.lint }}
        run: ./bin/ameba

      - name: Install SQLite3
        run: bash .github/install_sqlite.sh

      - name: Run migrations
        run: crystal sam.cr db:setup

      - name: Run specs
        run: crystal spec
